# -*- coding: utf-8 -*-
"""Para web.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j7Ok2OBxtMmqK8cdjTf1MbOwP5llTcnD
"""

import zipfile
import requests
import cv2
import matplotlib.pyplot as plt
import glob
import random
import os